USE [db_visual_mirassol_teste]
GO

/****** Object:  StoredProcedure [dbo].[PI_GERA_PEDIDO_PRC]    Script Date: 29/06/2020 20:46:01 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROC [dbo].[PI_GERA_PEDIDO_PRC] (
	@FILIAL INT --Filial Pedido
	,@CNPJ_PAGADOR VARCHAR(20) --Codigo Pagador
	,@CNPJ_REMETENTE VARCHAR(20) --Codigo Remetente
	,@CNPJ_TERMINAL_ENTREGA VARCHAR(20) --Codigo Terminal Entrega - inserido por Cesar em 10-12-2018
	,@LINHA VARCHAR(6) --Codigo da Linha
	,@CODPTC INT --Código Tipo de Carga
	,@DATRET SMALLDATETIME --Data Retirada
	,@DATENT SMALLDATETIME --Data Entrega
	,@CNPJ_DESTINATARIO VARCHAR(20) --Codigo Destinatario
	,@REFCLI VARCHAR(500) --Rota
	,@OBSERV VARCHAR(500) --Observação do tipo de Veículo
	,@PESOKG DECIMAL(12, 4) --Peso
	,@VOLUME INT --Volume
	,@EMERGENCIAL CHAR(1) -- 'S' para Sim ou 'N' para Não
	,@PEDIDO INT --Pedido Integrator
	,@CUBAGEM DECIMAL(12, 4) --Peso Cubado
	,@DIFERE VARCHAR(50) -- DIFERENCIAL
	,@RETORNO AS VARCHAR(100) OUTPUT
	)
AS
DECLARE @PAGADOR INT
DECLARE @REMETENTE INT
DECLARE @DESTINATARIO INT
DECLARE @TERMINAL_ENTREGA INT

SELECT @PAGADOR = codclifor
FROM rodcli
WHERE codcgc = @CNPJ_PAGADOR

SELECT @REMETENTE = codclifor
FROM rodcli
WHERE codcgc = @CNPJ_REMETENTE

SELECT @DESTINATARIO = codclifor
FROM rodcli
WHERE codcgc = @CNPJ_DESTINATARIO

SELECT @TERMINAL_ENTREGA = codclifor
FROM rodcli
WHERE codcgc = @CNPJ_TERMINAL_ENTREGA

DECLARE @CODIGO_NOVO AS INTEGER

--BUSCA O PROXIMO CODIGO DA PC
SET @CODIGO_NOVO = (
		SELECT MAX(ISNULL(PC.CODIGO, 0)) + 1
		FROM RODPRC PC
		WHERE PC.CODFIL = @FILIAL
		)

INSERT INTO RODPRC (
	CODFIL -- CAMPO 01
	,CODIGO -- CAMPO 02
	,DATATU -- CAMPO 03
	,USUATU -- CAMPO 04
	,DATINC -- CAMPO 05
	,USUINC -- CAMPO 06
	,SITUAC -- CAMPO 07
	,ALOCAD -- CAMPO 08
	,DATRET -- CAMPO 09
	,DATENT -- CAMPO 10
	,CODICO -- CAMPO 11
	,CODREM -- CAMPO 12
	,CODTOM -- CAMPO 13
	,CODPAD -- CAMPO 14
	,CODLIN -- CAMPO 15
	,CODPTC -- CAMPO 16
	,DATREF -- CAMPO 17
	,CONTAT -- CAMPO 18
	,TELEFO -- CAMPO 19
	,NRAMAL -- CAMPO 20
	,NUMFAX -- CAMPO 21
	,QUANTI -- CAMPO 22
	,PESRET -- CAMPO 23
	,DATCAN -- CAMPO 24
	,DATBAI -- CAMPO 25
	,FREPES -- CAMPO 26
	,FREVLR -- CAMPO 27
	,SECCAT -- CAMPO 28
	,DESPAC -- CAMPO 29
	,VLRADM -- CAMPO 30
	,TAREST -- CAMPO 31
	,VLRITR -- CAMPO 32
	,VLRPED -- CAMPO 33
	,VLRCAR -- CAMPO 34
	,VLRDES -- CAMPO 35
	,VLRCOL -- CAMPO 36
	,VLRENT -- CAMPO 37
	,VLRADI -- CAMPO 38
	,DESADI -- CAMPO 39
	,VLRTOT -- CAMPO 40
	,PRIORI -- CAMPO 41
	,BASCAL -- CAMPO 42
	,ALIQUO -- CAMPO 43
	,VLRICM -- CAMPO 44
	,VLRSEG -- CAMPO 45
	,COMFRE -- CAMPO 46
	,CONTAI -- CAMPO 47
	,NOMPOR -- CAMPO 48
	,FREETM -- CAMPO 49
	,PADCTN -- CAMPO 50
	,AGENAV -- CAMPO 51
	,NUMCTN -- CAMPO 52
	,DIGCTN -- CAMPO 53
	,COMCTN -- CAMPO 54
	,TARCTN -- CAMPO 55
	,REGIME -- CAMPO 56
	,LOCATR -- CAMPO 57
	,NOMNAV -- CAMPO 58
	,DOCEXP -- CAMPO 59
	,TIPCTN -- CAMPO 60
	,BRUCTN -- CAMPO 61
	,NUMLAC -- CAMPO 62
	,LACPRO -- CAMPO 63
	,TERCOL -- CAMPO 64
	,TERENT -- CAMPO 65
	,CODREG -- CAMPO 66
	,CRIIMP -- CAMPO 67
	,CRIEXP -- CAMPO 68
	,CRIATE -- CAMPO 69
	,CRIPRA -- CAMPO 70
	,CRIEQU -- CAMPO 71
	,CRIOBS -- CAMPO 72
	,RESERV -- CAMPO 73
	,AEREO -- CAMPO 74
	,NUMEDI -- CAMPO 75
	,NUDTAE -- CAMPO 76
	,NUDTA1 -- CAMPO 77
	,NUDTAS -- CAMPO 78
	,NUMAWB -- CAMPO 79
	,NUHAWB -- CAMPO 80
	,PLACA -- CAMPO 81
	,CODPOR -- CAMPO 82
	,DESICM -- CAMPO 83
	,OBSCON -- CAMPO 84
	,OBSFIS -- CAMPO 85
	,VLDES2 -- CAMPO 86
	,CODFRO -- CAMPO 87
	,TIPCAL -- CAMPO 88
	,VALCAL -- CAMPO 89
	,CODRED -- CAMPO 90
	,OBSERV -- CAMPO 91
	,TEMPER -- CAMPO 92
	,VENTIL -- CAMPO 93
	,HUMIDA -- CAMPO 94
	,METCUB -- CAMPO 95
	,IMPEXP -- CAMPO 96
	,COPAWB -- CAMPO 97
	,COPHAW -- CAMPO 98
	,AGECAR -- CAMPO 99
	,CODCIA -- CAMPO 100
	,EDIARQ -- CAMPO 101
	,MUNTOM -- CAMPO 102
	,MUNREM -- CAMPO 103
	,CODCIE -- CAMPO 104
	,ID_ENDCOL -- CAMPO 105
	,CARIMO -- CAMPO 106
	,CODCOL -- CAMPO 107
	,SERCOL -- CAMPO 108
	,FILCOL -- CAMPO 109
	,TAXVAR -- CAMPO 110
	,FILDES -- CAMPO 111
	,PORENT -- CAMPO 112
	,DIFERE -- CAMPO 113
	,CODORD -- CAMPO 114
	,SERORD -- CAMPO 115
	,FILORD -- CAMPO 116
	,TAXESP -- CAMPO 117
	,CODAUX -- CAMPO 118
	,NUMINV -- CAMPO 119
	,NUMAGE -- CAMPO 120
	,DATFAT -- CAMPO 121
	,CARURG -- CAMPO 122
	,CODFRE -- CAMPO 123
	,NUMCTR -- CAMPO 124
	,FERROV -- CAMPO 125
	,CODCTS -- CAMPO 126
	,VLRGRI -- CAMPO 127
	,VEIRET -- CAMPO 128
	,STSAPR -- CAMPO 129
	,CONRED -- CAMPO 130
	,REDMUN -- CAMPO 131
	,INCIDE_ST -- CAMPO 132
	,BASCAL_ST -- CAMPO 133
	,VLRICM_ST -- CAMPO 134
	,ALICOT_ST -- CAMPO 135
	,VLRCTN -- CAMPO 136
	,CODOSA -- CAMPO 137
	,FILOSA -- CAMPO 138
	,CODTAL -- CAMPO 139
	,CAREXT -- CAMPO 140
	,CODCST -- CAMPO 141
	,VIAINT -- CAMPO 142
	,CODHOR -- CAMPO 143
	,FILCOT -- CAMPO 144
	,CODCOT -- CAMPO 145
	,MODELO -- CAMPO 146
	,INTNAL -- CAMPO 147
	,TIPCOV -- CAMPO 148
	,METCOV -- CAMPO 149
	,DIASCV -- CAMPO 150
	,DTCONV -- CAMPO 151
	)
SELECT 
	@FILIAL -- CAMPO 01
	,@CODIGO_NOVO -- CAMPO 02
	,GETDATE() -- CAMPO 03
	,'INTEGRATOR' -- CAMPO 04
	,GETDATE() -- CAMPO 05
	,'INTEGRATOR' -- CAMPO 06
	,'D' -- CAMPO 07
	,'N' -- CAMPO 08
	,@DATRET -- CAMPO 09
	,@DATENT -- CAMPO 10
	,CODICO -- CAMPO 11
	,@REMETENTE -- CAMPO 12
	,@PAGADOR -- CAMPO 13
	,CODPAD -- CAMPO 14
	,@LINHA -- CAMPO 15
	,@CODPTC -- CAMPO 16
	,GETDATE() -- CAMPO 17
	,CONTAT -- CAMPO 18
	,TELEFO -- CAMPO 19
	,NRAMAL -- CAMPO 20
	,NUMFAX -- CAMPO 21
	,QUANTI -- CAMPO 22
	,PESRET -- CAMPO 23
	,DATCAN -- CAMPO 24
	,DATBAI -- CAMPO 25
	,FREPES -- CAMPO 26
	,FREVLR -- CAMPO 27
	,SECCAT -- CAMPO 28
	,DESPAC -- CAMPO 29
	,VLRADM -- CAMPO 30
	,TAREST -- CAMPO 31
	,VLRITR -- CAMPO 32
	,VLRPED -- CAMPO 33
	,VLRCAR -- CAMPO 34
	,VLRDES -- CAMPO 35
	,VLRCOL -- CAMPO 36
	,VLRENT -- CAMPO 37
	,VLRADI -- CAMPO 38
	,DESADI -- CAMPO 39
	,VLRTOT -- CAMPO 40
	,PRIORI -- CAMPO 41
	,BASCAL -- CAMPO 42
	,ALIQUO -- CAMPO 43
	,VLRICM -- CAMPO 44
	,VLRSEG -- CAMPO 45
	,COMFRE -- CAMPO 46
	,CONTAI -- CAMPO 47
	,NOMPOR -- CAMPO 48
	,FREETM -- CAMPO 49
	,PADCTN -- CAMPO 50
	,AGENAV -- CAMPO 51
	,NUMCTN -- CAMPO 52
	,DIGCTN -- CAMPO 53
	,COMCTN -- CAMPO 54
	,TARCTN -- CAMPO 55
	,REGIME -- CAMPO 56
	,LOCATR -- CAMPO 57
	,NOMNAV -- CAMPO 58
	,DOCEXP -- CAMPO 59
	,TIPCTN -- CAMPO 60
	,BRUCTN -- CAMPO 61
	,NUMLAC -- CAMPO 62
	,LACPRO -- CAMPO 63
	,TERCOL -- CAMPO 64
	,@TERMINAL_ENTREGA -- CAMPO 65
	,-- INSERIDO VARIAVEL TERMINAL DE ENTREGA POR CESAR - 10-12-2018 -- CAMPO 66
	(
		SELECT codreg
		FROM rodlin
		WHERE codlin = @LINHA
		)
	,CRIIMP -- CAMPO 67
	,CRIEXP -- CAMPO 68
	,CRIATE -- CAMPO 69
	,CRIPRA -- CAMPO 70
	,CRIEQU -- CAMPO 71
	,CRIOBS -- CAMPO 72
	,RESERV -- CAMPO 73
	,'N' -- CAMPO 74
	,NUMEDI -- CAMPO 75
	,NUDTAE -- CAMPO 76
	,NUDTA1 -- CAMPO 77
	,NUDTAS -- CAMPO 78
	,NUMAWB -- CAMPO 79
	,NUHAWB -- CAMPO 80
	,'IMP0000' -- CAMPO 81
	,CODPOR -- CAMPO 82
	,DESICM -- CAMPO 83
	,OBSCON -- CAMPO 84
	,OBSFIS -- CAMPO 85
	,VLDES2 -- CAMPO 86
	,CODFRO -- CAMPO 87
	,TIPCAL -- CAMPO 88
	,VALCAL -- CAMPO 89
	,CODRED -- CAMPO 90
	,OBSERV -- CAMPO 91
	,TEMPER -- CAMPO 92
	,VENTIL -- CAMPO 93
	,HUMIDA -- CAMPO 94
	,METCUB -- CAMPO 95
	,IMPEXP -- CAMPO 96
	,COPAWB -- CAMPO 97
	,COPHAW -- CAMPO 98
	,AGECAR -- CAMPO 99
	,CODCIA -- CAMPO 100
	,EDIARQ -- CAMPO 101
	,(
		SELECT codmun
		FROM rodcli
		WHERE codclifor = @PAGADOR
		) -- CAMPO 102
	,(
		SELECT codmun
		FROM rodcli
		WHERE codclifor = @REMETENTE
		) -- CAMPO 103
	,CODCIE -- CAMPO 104
	,ID_ENDCOL -- CAMPO 105
	,CARIMO -- CAMPO 106
	,CODCOL -- CAMPO 107
	,SERCOL -- CAMPO 108
	,FILCOL -- CAMPO 109
	,TAXVAR -- CAMPO 110
	,@FILIAL -- CAMPO 111
	,PORENT -- CAMPO 112
	,@DIFERE -- CAMPO 113
	,CODORD -- CAMPO 114
	,SERORD -- CAMPO 115
	,FILORD -- CAMPO 116
	,'N' -- CAMPO 117
	,CODAUX -- CAMPO 118
	,@PEDIDO -- CAMPO 119
	,NUMAGE -- CAMPO 120
	,DATFAT -- CAMPO 121
	,@EMERGENCIAL -- CAMPO 122
	,CODFRE -- CAMPO 123
	,NUMCTR -- CAMPO 124
	,FERROV -- CAMPO 125
	,CODCTS -- CAMPO 126
	,VLRGRI -- CAMPO 127
	,VEIRET -- CAMPO 128
	,STSAPR -- CAMPO 129
	,CONRED -- CAMPO 130
	,REDMUN -- CAMPO 131
	,INCIDE_ST -- CAMPO 132
	,BASCAL_ST -- CAMPO 133
	,VLRICM_ST -- CAMPO 134
	,ALICOT_ST -- CAMPO 135
	,VLRCTN -- CAMPO 136
	,CODOSA -- CAMPO 137
	,FILOSA -- CAMPO 138
	,CODTAL -- CAMPO 139
	,CAREXT -- CAMPO 140
	,CODCST -- CAMPO 141
	,VIAINT -- CAMPO 142
	,CODHOR -- CAMPO 143
	,FILCOT -- CAMPO 144
	,CODCOT -- CAMPO 145
	,'N' -- CAMPO 146
	,INTNAL -- CAMPO 147
	,TIPCOV -- CAMPO 148
	,METCOV -- CAMPO 149
	,DIASCV -- CAMPO 150
	,DTCONV -- CAMPO 151
FROM RODPRC
WHERE CODIGO = 4
	AND CODFIL = 1

IF EXISTS (
		SELECT 1
		FROM rodprc A
		WHERE A.codfil = @FILIAL
			AND A.codigo = @CODIGO_NOVO
		)
BEGIN
	INSERT INTO RODIPR (
		ID_IPR -- CAMPO 1
		,CODFIL -- CAMPO 2
		,CODIGO -- CAMPO 3
		,DATATU -- CAMPO 4
		,USUATU -- CAMPO 5
		,DATINC -- CAMPO 6
		,USUINC -- CAMPO 7
		,SITUAC -- CAMPO 8
		,QTDRET -- CAMPO 9
		,PESRET -- CAMPO 10
		,CODPROTR -- CAMPO 11
		,CODDES -- CAMPO 12
		,SERIEN -- CAMPO 13
		,NUMNOT -- CAMPO 14
		,DATNOT -- CAMPO 15
		,ESPECI -- CAMPO 16
		,LARGUR -- CAMPO 17
		,ALTURA -- CAMPO 18
		,PROFUN -- CAMPO 19
		,QUANTI -- CAMPO 20
		,PESOKG -- CAMPO 21
		,PESCUB -- CAMPO 22
		,PESCAL -- CAMPO 23
		,EMPMAX -- CAMPO 24
		,VLRMER -- CAMPO 25
		,ORDCOM -- CAMPO 26
		,ITECOM -- CAMPO 27
		,ID_ENDENT -- CAMPO 28
		,VMERSE -- CAMPO 29
		,OBSERV -- CAMPO 30
		,CUBAGE -- CAMPO 31
		,NATURE -- CAMPO 32
		,TERCOL -- CAMPO 33
		,TERENT -- CAMPO 34
		,CODFIS -- CAMPO 35
		,FREPES -- CAMPO 36
		,FREVLR -- CAMPO 37
		,SECCAT -- CAMPO 38
		,DESPAC -- CAMPO 39
		,VLRADM -- CAMPO 40
		,TAREST -- CAMPO 41
		,VLRITR -- CAMPO 42
		,VLRPED -- CAMPO 43
		,VLRCAR -- CAMPO 44
		,VLRDES -- CAMPO 45
		,VLRCOL -- CAMPO 46
		,VLRENT -- CAMPO 47
		,VLRADI -- CAMPO 48
		,VLRTOT -- CAMPO 49
		,BASCAL -- CAMPO 50
		,ALIQUO -- CAMPO 51
		,VLRICM -- CAMPO 52
		,VLRSEG -- CAMPO 53
		,EDILOC -- CAMPO 54
		,EDIOPE -- CAMPO 55
		,NUMENT -- CAMPO 56
		,MUNDES -- CAMPO 57
		,RESERV -- CAMPO 58
		,NUMCTN -- CAMPO 59
		,DIGCTN -- CAMPO 60
		,COMCTN -- CAMPO 61
		,TARCTN -- CAMPO 62
		,TIPCTN -- CAMPO 63
		,NOTNFE -- CAMPO 64
		,NUMLAC -- CAMPO 65
		,NUMCOL -- CAMPO 66
		,RETCTN -- CAMPO 67
		,ENTCTN -- CAMPO 68
		,NUMAWB -- CAMPO 69
		,NUHAWB -- CAMPO 70
		,NUMPIN -- CAMPO 71
		,TIPUNI -- CAMPO 72
		,IDEUNI -- CAMPO 73
		,CODCTC -- CAMPO 74
		)
	SELECT TOP 1 (
			SELECT ISNULL(MAX(ID_IPR), 0) + 1
			FROM RODIPR
			) -- CAMPO 1
		,@FILIAL -- CAMPO 2
		,@CODIGO_NOVO -- CAMPO 3
		,GETDATE() -- CAMPO 4
		,'INTEGRATOR' -- CAMPO 5
		,GETDATE() -- CAMPO 6
		,'INTEGRATOR' -- CAMPO 7
		,'D' -- CAMPO 8
		,0 -- CAMPO 9
		,0 -- CAMPO 10
		,CODPROTR -- CAMPO 11
		,@DESTINATARIO -- CAMPO 12
		,'99' -- CAMPO 13
		,NUMNOT -- CAMPO 14
		,DATNOT -- CAMPO 15
		,ESPECI -- CAMPO 16
		,LARGUR -- CAMPO 17
		,ALTURA -- CAMPO 18
		,PROFUN -- CAMPO 19
		,@VOLUME -- CAMPO 20
		,@PESOKG -- CAMPO 21
		,@CUBAGEM -- CAMPO 22
		,PESCAL -- CAMPO 23
		,EMPMAX -- CAMPO 24
		,VLRMER -- CAMPO 25
		,@REFCLI -- CAMPO 26
		,ITECOM -- CAMPO 27
		,ID_ENDENT -- CAMPO 28
		,VMERSE -- CAMPO 29
		,@OBSERV -- CAMPO 30
		,CUBAGE -- CAMPO 31
		,NATURE -- CAMPO 32
		,TERCOL -- CAMPO 33
		,TERENT -- CAMPO 34
		,CODFIS -- CAMPO 35
		,FREPES -- CAMPO 36
		,FREVLR -- CAMPO 37
		,SECCAT -- CAMPO 38
		,DESPAC -- CAMPO 39
		,VLRADM -- CAMPO 40
		,TAREST -- CAMPO 41
		,VLRITR -- CAMPO 42
		,VLRPED -- CAMPO 43
		,VLRCAR -- CAMPO 44
		,VLRDES -- CAMPO 45
		,VLRCOL -- CAMPO 46
		,VLRENT -- CAMPO 47
		,VLRADI -- CAMPO 48
		,VLRTOT -- CAMPO 49
		,BASCAL -- CAMPO 50
		,ALIQUO -- CAMPO 51
		,VLRICM -- CAMPO 52
		,VLRSEG -- CAMPO 53
		,EDILOC -- CAMPO 54
		,EDIOPE -- CAMPO 55
		,NUMENT -- CAMPO 56
		,(
			SELECT codmun
			FROM rodcli
			WHERE codclifor = @DESTINATARIO
			) -- CAMPO 57
		,RESERV -- CAMPO 58
		,NUMCTN -- CAMPO 59
		,DIGCTN -- CAMPO 60
		,COMCTN -- CAMPO 61
		,TARCTN -- CAMPO 62
		,TIPCTN -- CAMPO 63
		,NOTNFE -- CAMPO 64
		,NUMLAC -- CAMPO 65
		,NUMCOL -- CAMPO 66
		,RETCTN -- CAMPO 67
		,ENTCTN -- CAMPO 68
		,NUMAWB -- CAMPO 69
		,NUHAWB -- CAMPO 70
		,NUMPIN -- CAMPO 71
		,TIPUNI -- CAMPO 72
		,IDEUNI -- CAMPO 73
		,CODCTC -- CAMPO 74
	FROM RODIPR
	WHERE CODFIL = 1
		AND CODIGO = 4
END

SET @RETORNO = CAST(@FILIAL AS VARCHAR(10)) + '-' + CAST(@CODIGO_NOVO AS VARCHAR(100))

--exec PI_GERA_PEDIDO_PRC 
--1, --Filial Pedido
--119, --Codigo Pagador
--1532, --Codigo Remetente
--'IPVGAj', --Codigo da Linha
--1, --Código Tipo de Carga
--'2018-06-19', --Data Retirada
--'2018-06-19', --Data Entrega
--119, --Codigo Destinatario
--'SP-001', --Rota
--'Utilizar Carreta', --Observação do tipo de Veículo
--0, --Peso
--0, --Volume
--'S', -- 'S' para Sim ou 'N' para Não
--1002344,  --Pedido Integrator
--NULL --Retorno
/*SELECT TOP 10 AEREO
	,*
FROM RODPRC
WHERE codigo = 2083
	AND codfil = 39
	*/
GO


